version: "3.5"

services:
  vescollector:
    restart: unless-stopped
    ports:
      - "8080:8080/udp"
    network_mode: host
    image: nexus3.onap.org:10001/onap/org.onap.dcaegen2.collectors.ves.vescollector:latest
    container_name: vescollector
    environment:
      DMAAPHOST: 50.50.50.50

  ves-nf-oam-adopter-ran-mock:
    ports:
      - "443:443/tcp"
    network_mode: host
    restart: unless-stopped
    image: nexus3.o-ran-sc.org:10004/o-ran-sc/ves-nf-oam-adopter-ran-mock:latest
    container_name: ves-nf-oam-adopter-ran-mock
    environment:
      KEY_PASSWORD: nf-oam-adopter
      KEY_STORE_PASSWORD: nf-oam-adopter
      SNMP-DESTINY: 0.0.0.0/162
      SERVER_PORT: 443

  ves-nf-oam-adopter:
    ports:
      - "443:444/tcp"
    network_mode: host
    restart: unless-stopped
    image: nexus3.o-ran-sc.org:10004/o-ran-sc/ves-nf-oam-adopter:latest
    container_name: ves-nf-oam-adopter
    environment:
      SERVER_PORT: 444
      USERNAME: admin
      PASSWORD: admin
      KEY_PASSWORD: nf-oam-adopter
      KEY_STORE_PASSWORD: nf-oam-adopter
      TRUST_STORE_PASSWORD: nf-oam-adopter
      VES_COLLECTOR: http://0.0.0.0:8080/eventListener/v7
      VES_ENCODED_AUTH: YWRtaW46YWRtaW4=
      PM_SYNC_TIME_START: "14:25:00"
      PM_SYNC_TIME_FREQ: 30