#  ============LICENSE_START=======================================================
#  Copyright © 2021 AT&T Intellectual Property. All rights reserved.
#  ================================================================================
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
#  SPDX-License-Identifier: Apache-2.0
#  ============LICENSE_END=========================================================
openapi: 3.0.3
info:
  title: O-RAN OAM Adopter RAN Mock
  description: API for O-RAN OAM Adopter RAN Mock service.
  version: "1.0.0"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0"

servers:
  - url: https://example.io/v1

paths:
  /auth/token:
    post:
      security:
        - BasicAuth: [ ]
      tags:
        - controller
      summary: Generate token
      description: Generate token
      operationId: authenticateAndGenerateToken
      responses:
        '200':
          description: Successfully returned a list of adapters host address
          content:
            application/json:
              schema:
                type: string
        '400':
          $ref: '#/components/responses/400Error'
        '401':
          $ref: '#/components/responses/401Error'
  /pm/files:
    post:
      tags:
        - controller
      summary: Read Performance Management Files
      description: Read Performance Management Files
      operationId: getPerformanceManagementFiles
      responses:
        '200':
          description: Successfully returned ZIP with CSV pm files
          content:
            application/zip:
              schema:
                type: string
                format: binary
        '400':
          $ref: '#/components/responses/400Error'
        '401':
          $ref: '#/components/responses/401Error'
  /system/timeZone:
    post:
      tags:
        - controller
      summary: Read time zone
      description: Read time zone
      operationId: getTimeZone
      responses:
        '200':
          description: Successfully returned time zone of the RAN
          content:
            application/json:
              schema:
                type: string
        '400':
          $ref: '#/components/responses/400Error'
        '401':
          $ref: '#/components/responses/401Error'

components:
  responses:
    400Error:
      description: Invalid request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
    401Error:
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string